=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Схема Конфигурации Корабля",
	"description": "Конфигурация корабля, используемая для определения новых классов кораблей.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Название Класса",
			"type": "string",
			"description": "Название класса корабля, отображаемое в игре. Суффикс «-class» должен быть в нижнем регистре."
		},
		"map_short_name": {
			"title": "Сокращённое Название Класса",
			"type": "string",
			"description": "Сокращённая версия названия класса корабля, используется, например, в манифесте, а также используется для просмотр карт при покупке корабля, ссылаясь на сайт https://map.celadon.pro. Пробелы и символы запрещены. Исключения:'-' и '_'",
			"maxLength": 20
		},
		"description": {
			"title": "Описание Класса",
			"type": "string",
			"description": "Описание класса корабля. В настоящее время отображается показывается для игроков перед покупкой корабля, а также для администраторов в инструментах управления шаттлом.",
			"minLength": 250
		},
		"map_path": {
			"title": "Путь к Файлу Карты",
			"type": "string",
			"description": "Путь к файлу карты данного класса корабля. Используйте прямые слэши (/) для директорий и включайте расширение .dmm. Файлы карт должны находиться в папке '_maps/_mod_celadon'.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"subshuttle": {
			"title": "Название Субшаттла",
			"type": "string",
			"description": "Название Субшаттла, что добавлен на карту материнского корабля. Используется для дополнительного вывода информации при покупке корабля, а также для ссылки на карту субшаттла на сайте корабля."
		},
		"enabled": {
			"title": "Доступность",
			"type": "boolean",
			"description": "Можно ли выбрать этот корабль игрокам. Админы всё равно смогут его заспавнить.",
			"default": false
		},
		"roundstart": {
			"title": "Случайный Выбор на Старте Раунда",
			"type": "boolean",
			"description": "Определяет, может ли этот корабль быть случайно выбран в качестве бесплатного стартового корабля.",
			"default": false
		},
		"limit": {
			"title": "Ограничение на Спавн Кораблей",
			"type": "integer",
			"description": "Максимальное количество кораблей этого класса, которое может быть заспавнено игроками за раунд.",
			"minimum": 0,
			"maximum": 100,
			"default": 1
		},
		"sensor_range": {
			"title": "Дальность Сенсоров",
			"type": "number",
			"description": "Определяет максимальную дальность сенсоров корабля."
		},
		"starting_funds": {
			"title": "Стартовые Средства Корабля",
			"type": "integer",
			"description": "Количество денег на банковском счёте корабля при старте.",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"space_spawn": {
			"title": "Спавн в Космосе",
			"type": "boolean",
			"description": "Определяет, появится ли корабль в космосе или на аванпосте.",
			"default": false
		},
		"prefix": {
			"title": "Префикс Корабля",
			"type": ["null", "string"],
			"description": "Префикс класса корабля, который добавляется к случайно сгенерированным именам при покупке.",
			"maxLength": 6
		},
		"faction": {
			"title": "Фракция Корабля",
			"type": "string",
			"pattern": "^/datum/faction/(.*)$",
			"description": "Фракция по умолчанию."
		},
		"manufacturer": {
			"title": "Производитель Корабля",
			"type": ["null", "string"],
			"description": "Производитель класса корабля, в данный момент не используется, но будет использоваться в автоматических вики-шаблонах."
		},
		"tags": {
			"title": "Теги Корабля",
			"type": "array",
			"description": "Список тегов, описывающих особенности корабля, которые можно использовать для поиска."
		},
		"namelists": {
			"title": "Списки Имен",
			"type": "array",
			"description": "Список имен, из которого этот класс корабля будет выбирать случайное имя при покупке. Все варианты можно найти в файле ship_names.json.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"NANOTRASEN",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLFED",
					"CMM-GOLD",
					"CMM-BARD",
					"PGF"
				]
			}
		},
		"job_slots": {
			"title": "Рабочие Места",
			"description": "Список рабочих мест, доступных на этом корабле. Первый слот всегда отводится под 'капитана', которым становится покупатель.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "Предустановленная должность, должна совпадать с названием работы в коде (названия работ можно найти в соответствующих файлах)."
					},
					{
						"type": "object",
						"description": "Пользовательская должность, может быть любым названием, но требует указания униформы и количества слотов.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "Название униформы (outfit), которая будет использоваться в этом слоте. Должно быть точным, иначе вызовет ошибку.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Определяет, является ли должность офицерской. Офицерские должности получают шеврон в манифесте, а количество их слотов нельзя изменять в игре.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "Количество доступных мест в этом слоте при старте раунда. Экипаж может изменить его в игре, но не более чем вдвое.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"spawn_time_coeff": {
			"title": "Коэффициент Времени Спавна",
			"type": "number",
			"description": "Множитель, используемый для расчёта минимального времени игры в живом состоянии, необходимого для спавна этого корабля.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Коэффициент Времени Офицера",
			"type": "number",
			"description": "Множитель, определяющий минимальное время игры в живом состоянии, необходимое для спавна в офицерской должности на этом корабле.",
			"minimum": 0,
			"default": 1
		}
	},
		"required": [
		"map_name",
		"map_short_name",
		"map_path",
		"faction",
		"job_slots"
	]
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/solfed_firetail.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Firetail-class Expeditionary Frigate",
	"map_short_name": "Firetail",
	"description": "Фрегат класса 'Firetail' с субшаттлом класса 'Vespa' на борту - новейший экспедиционный корабль флота Солнечной Федерации. Он отличается высокой для своей весовой категории тягой, наличием отделения телекоммуникаций и сбалансированным оборудованием, идеально подходящим для долгих миссий в далёком космосе.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_firetail.dmm",
	"subshuttle": "Vespa",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "SPSFSV",
	"faction": "/datum/faction/solgov",
	"tags": [
		"Боевой",
		"Суб-шаттл"
	],
	"namelists": [
		"SOLFED",
		"BRITISH_NAVY"
	],
	"job_slots": {
		"Kommandant": {
			"outfit": "/datum/outfit/job/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Expeditionary Feldwebel": {
			"outfit": "/datum/outfit/job/solfed/sergeant",
			"officer": true,
			"slots": 1
		},
		"Expeditionary Marine": {
			"outfit": "/datum/outfit/job/solfed/marine",
			"slots": 3
		},
		"Expeditionary Meeresarzt": {
			"outfit": "/datum/outfit/job/solfed/doctor",
			"slots": 1
		},
		"Expeditionary Marinemechaniker": {
			"outfit": "/datum/outfit/job/solfed/engineer",
			"slots": 1
		},
		"Meeresarzt": {
			"outfit": "/datum/outfit/job/solfed/doctor",
			"slots": 1
		},
		"Marinemechaniker": {
			"outfit": "/datum/outfit/job/solfed/engineer",
			"slots": 1
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/solfed_chronicle.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Chronicle-class Sensor Frigate",
	"map_short_name": "Chronicle",
	"description": "Оснащенный сложным набором сенсоров и мощными утилитами для работы с данными, 'Chronicle' - это канцелярская рабочая лошадка, способная собирать и обрабатывать огромные объемы информации. Часто используемый для переписи населения и межзвездных исследований, 'Chronicle' также является фаворитом Evidenzkompanien, часто используемым для разведывательных операций. Учитывая этот факт, судна класса 'Chronicle' часто подвергаются повышенному контролю со стороны патрулей, что несколько снижает их эффективность как инструмента шпионажа. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Заменен на другой шип Firetale!",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_chronicle.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "SFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["Исследовательский"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"BRITISH_NAVY",
		"NATURAL"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Aufseher": {
			"outfit": "/datum/outfit/job/solfed/hop",
			"officer": true,
			"slots": 1
		},
		"Sonnensöldner": {
			"outfit": "/datum/outfit/job/solfed/marine",
			"slots": 1
		},
		"Ship Engineer": {
			"outfit": "/datum/outfit/job/solfed/engineer",
			"slots": 2
		},
		"Field Engineer": {
			"outfit": "/datum/outfit/job/solfed/miner",
			"slots": 2
		},
		"Scribe": {
			"outfit": "/datum/outfit/job/solfed/assistant",
			"slots" : 2
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/solfed_lightning.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Lightning Medical Light-Cruiser",
	"map_short_name": "Lightning",
	"description": " 'Lightning',  Модернизированная и переоборудованная версия одного из первых разведывательных космических кораблей регулярных сил Солнечной Федерации во времена космической экспансии о чем говорит его обшивка из сплава плазмы и титана черного цвета . Корабль оснащен современным медицинским оборудованием для поддержки союзных кораблей, а так же гумманитарных миссий на просторах Фронтира, а так же двигатели позволяющие развивать огромную скорость оправдывающие его название",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_lightning.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 7,
	"starting_funds": 2000,
	"prefix": "MSFSV",
	"faction": "/datum/faction/solgov",
	"tags": [
	"Медицинское"
	],
	"namelists": [
		"SOLFED",
		"SPACE",
		"BRITISH_NAVY",
		"NATURAL"
	],
	"job_slots": {
		"Kommandant": {
			"outfit": "/datum/outfit/job/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Marine Guard": {
			"outfit": "/datum/outfit/job/solfed/sergeant",
			"officer": true,
			"slots": 1
		},
		"Medical Scientist": {
			"outfit": "/datum/outfit/job/solfed/doctor",
			"slots":1
		},
		"Meeresarzt": {
			"outfit": "/datum/outfit/job/solfed/doctor",
			"slots": 2
		},
		"Field Marinemechaniker": {
			"outfit": "/datum/outfit/job/solfed/engineer",
			"slots": 2
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/solfed_inkwell.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Inkwell-class Supply Freighter",
	"map_short_name": "Inkwell",
	"description": "Одно из немногих суден, спроектированных Солом и используемых вне официального контекста сторонами, не входящими в Конфедерацию, Судно класса 'Inkwell' - грузовое судно, уважаемое за свою инженерную мысль и любимое за роскошные помещения для экипажа. \n 'Inkwell' можно встретить во многих контекстах, но, пожалуй, больше всего среди Вервальтунгскомпаниен, где они играют важную роль в решении логистических проблем любой надлежащей военной администрации. Кроме того, их часто заказывают и продают несоларианцам для использования в межзвездных перевозках. \n Об использовании 'Inkwell' для перевозки незаконных или неотслеживаемых грузов известно любому опытному (или даже полуопытному) портовому начальству; \n '...такие прискорбные действия со стороны исключительного меньшинства - лишь часть реалий межзвездных перевозок, \n' - говорится в официальном ответе.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_inkwell.dmm",
	"subshuttle": "Feather",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "SSFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["RP Focus", "Combat", "Cargo", "Mining", "Subshuttle"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"BRITISH_NAVY",
		"NATURAL"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Logistics Deck Officer": {
			"outfit": "/datum/outfit/job/solfed/quartermaster",
			"officer": true,
			"slots": 1
		},
		"Sonnensöldner": {
			"outfit": "/datum/outfit/job/solfed/marine",
			"slots": 3
		},
		"Ship Engineer": {
			"outfit": "/datum/outfit/job/solfed/engineer",
			"slots": 2
		},
		"Field Engineer": {
			"outfit": "/datum/outfit/job/solfed/miner",
			"slots": 3
		},
		"Gehilfe": {
			"outfit": "/datum/outfit/job/solfed/assistant",
			"slots" : 6
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/independent_junker.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Junker-class Salvaged Ship",
	"map_short_name": "Junker",
	"description": "Судно класса 'Junker' - это не официальный класс, а скорее название общей группы суден, созданных из руин старых суден или станций. Эти судна стали обычным явлением во время ICW, когда дезертиры бежали из зон конфликта на этих 'Junker's', не готовые к трудностям космической жизни. С тех пор они стали редкостью, а немногие выжившие экипажи этих суден обычно испытывают чувство презрения к обычным властным структурам и, как правило, не имеют определенного капитана или даже владельца судна.",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_junker.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 3,
	"starting_funds": 0,
	"prefix": "SV",
	"faction": "/datum/faction/independent",
	"tags": ["Survival Challenge"],
	"namelists": [
		"GENERAL",
		"SPACE"
	],
	"job_slots": {
		"Assistant": {
			"outfit": "/datum/outfit/job/assistant",
			"slots": 4
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/independent_pillbottle.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Pillbottle-class Locust Transport",
	"map_short_name": "Pillbottle",
	"description": "Pillbottle как класс вообще не должен существовать. Всё указывает на то, что эти корабли изначально были массовыми грузовиками и буксирами, но затем кое-как переделаны в подобие носителя для крыла спасательных капсул класса «Pill». Как и в случае с «Pills», экипажи «Pillbottle» полностью состоят из беглых заключённых, и по общему правилу они действуют в состоянии полной анархии. Единственное, что стабильно в экипажах «Pillbottle», — это их нестабильность, а тюремные реалии, как правило, вытягивают из любого человека самое худшее. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Он не должен существовать. Никем не переделывался.",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_pillbottle.dmm",
	"subshuttle": "Pill",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"starting_funds": 0,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": [
		"Специализированный"
	],
	"namelists": [
		"PILLS",
		"PIRATES"
	],
	"job_slots": {
		"Prisoner": {
			"outfit": "/datum/outfit/job/prisoner",
			"slots": 10
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/elysium_lalish.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Lalish-class Space Explosives Factory",
	"map_short_name": "Lalish",
	"description": "Корабли класса 'Лалиш' — это относительно недавно спроектированные и построенные на верфях сепаратистов Элизиума суда. Их основное назначение — производство взрывчатых веществ, таких как бомбы, гранаты и пластиковая взрывчатка... Для этого на борту предусмотрено все необходимое: химические реактивы, материалы, камера сгорания и прочее. Судно имеет компактные размеры, что делает его менее заметным, однако это негативно сказалось на удобстве планировки. Кроме того, его двигательная установка оставляет желать лучшего — корабль оснащен всего двумя ионными двигателями, которые с трудом справляются с его массой. В итоге мы имеем небольшой, малоскоростной, но все же способный передвигаться корабль с минимальным экипажем, вооруженным верой в Аллаха и взрывчаткой. Слава Республике! – Алмаждурин Джанхуриети!",
	"map_path": "_maps/_mod_celadon/shuttles/elysium/elysium_lalish.dmm",
	"enabled": true,
	"limit": 1,
	"prefix": "ESV",
	"faction": "/datum/faction/elysium",
	"tags": [
		"RP Focus",
		"Bombs",
		"Production"
	],
	"namelists": [
		"SPACE",
		"MAGICAL"
	],
	"job_slots": {
		"Caid": {
			"outfit": "/datum/outfit/job/elysium/captain",
			"officer": true,
			"slots": 1
		},
		"Ahisa`i": {
			"outfit": "/datum/outfit/job/elysium/assistant",
			"slots": 3
		}

	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/solfed_cepheus.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Cepheus-class Patrool Corvette",
	"map_short_name": "Cepheus",
	"description": "Корвет класса 'Cepheus' является патрульным судном Солнечной Федерации, предназначенный для поддержания порядка на территории планет NE-24774. Дополнительно оснащен роботехнической лабораторией в целях развертывания дополнительных наземных сил и оказания универсальной поддержки. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Не балансился, с рандомной платой меха раундстартом!",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_cepheus.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "BSFSV",
	"faction": "/datum/faction/solgov",
	"tags": [
		"Engineering",
		"Mining",
		"Robotics",
		"Combat"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"WEAPONS",
		"NATURAL"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Ship Engineer": {
			"outfit": "/datum/outfit/job/solfed/engineer",
			"slots": 1
		},
		"Sonnensöldner": {
			"outfit": "/datum/outfit/job/solfed/marine",
			"slots": 2
		},
		"Exosuit Operator": {
			"outfit": "/datum/outfit/job/solfed/marine/pilot",
			"slots": 2
		},
		"Mechanical Technician Officer": {
			"outfit": "/datum/outfit/job/solfed/scientist/roboticist",
			"slots": 1
		},
		"Scribe": {
			"outfit": "/datum/outfit/job/solfed/assistant",
			"slots" : 1
		}
	}
}
