=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Схема Конфигурации Корабля",
	"description": "Конфигурация корабля, используемая для определения новых классов кораблей.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Название Класса",
			"type": "string",
			"description": "Название класса корабля, отображаемое в игре. Суффикс «-class» должен быть в нижнем регистре."
		},
		"map_short_name": {
			"title": "Сокращённое Название Класса",
			"type": "string",
			"description": "Сокращённая версия названия класса корабля, используется, например, в манифесте, а также используется для просмотр карт при покупке корабля, ссылаясь на сайт https://map.celadon.pro. Пробелы и символы запрещены. Исключения:'-' и '_'",
			"maxLength": 20
		},
		"description": {
			"title": "Описание Класса",
			"type": "string",
			"description": "Описание класса корабля. В настоящее время отображается показывается для игроков перед покупкой корабля, а также для администраторов в инструментах управления шаттлом.",
			"minLength": 250
		},
		"map_path": {
			"title": "Путь к Файлу Карты",
			"type": "string",
			"description": "Путь к файлу карты данного класса корабля. Используйте прямые слэши (/) для директорий и включайте расширение .dmm. Файлы карт должны находиться в папке '_maps/_mod_celadon'.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"subshuttle": {
			"title": "Название Субшаттла",
			"type": "string",
			"description": "Название Субшаттла, что добавлен на карту материнского корабля. Используется для дополнительного вывода информации при покупке корабля, а также для ссылки на карту субшаттла на сайте корабля."
		},
		"enabled": {
			"title": "Доступность",
			"type": "boolean",
			"description": "Можно ли выбрать этот корабль игрокам. Админы всё равно смогут его заспавнить.",
			"default": false
		},
		"roundstart": {
			"title": "Случайный Выбор на Старте Раунда",
			"type": "boolean",
			"description": "Определяет, может ли этот корабль быть случайно выбран в качестве бесплатного стартового корабля.",
			"default": false
		},
		"limit": {
			"title": "Ограничение на Спавн Кораблей",
			"type": "integer",
			"description": "Максимальное количество кораблей этого класса, которое может быть заспавнено игроками за раунд.",
			"minimum": 0,
			"maximum": 100,
			"default": 1
		},
		"sensor_range": {
			"title": "Дальность Сенсоров",
			"type": "number",
			"description": "Определяет максимальную дальность сенсоров корабля."
		},
		"starting_funds": {
			"title": "Стартовые Средства Корабля",
			"type": "integer",
			"description": "Количество денег на банковском счёте корабля при старте.",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"space_spawn": {
			"title": "Спавн в Космосе",
			"type": "boolean",
			"description": "Определяет, появится ли корабль в космосе или на аванпосте.",
			"default": false
		},
		"prefix": {
			"title": "Префикс Корабля",
			"type": ["null", "string"],
			"description": "Префикс класса корабля, который добавляется к случайно сгенерированным именам при покупке.",
			"maxLength": 6
		},
		"faction": {
			"title": "Фракция Корабля",
			"type": "string",
			"pattern": "^/datum/faction/(.*)$",
			"description": "Фракция по умолчанию."
		},
		"manufacturer": {
			"title": "Производитель Корабля",
			"type": ["null", "string"],
			"description": "Производитель класса корабля, в данный момент не используется, но будет использоваться в автоматических вики-шаблонах."
		},
		"tags": {
			"title": "Теги Корабля",
			"type": "array",
			"description": "Список тегов, описывающих особенности корабля, которые можно использовать для поиска."
		},
		"namelists": {
			"title": "Списки Имен",
			"type": "array",
			"description": "Список имен, из которого этот класс корабля будет выбирать случайное имя при покупке. Все варианты можно найти в файле ship_names.json.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"NANOTRASEN",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLFED",
					"CMM-GOLD",
					"CMM-BARD",
					"PGF"
				]
			}
		},
		"job_slots": {
			"title": "Рабочие Места",
			"description": "Список рабочих мест, доступных на этом корабле. Первый слот всегда отводится под 'капитана', которым становится покупатель.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "Предустановленная должность, должна совпадать с названием работы в коде (названия работ можно найти в соответствующих файлах)."
					},
					{
						"type": "object",
						"description": "Пользовательская должность, может быть любым названием, но требует указания униформы и количества слотов.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "Название униформы (outfit), которая будет использоваться в этом слоте. Должно быть точным, иначе вызовет ошибку.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Определяет, является ли должность офицерской. Офицерские должности получают шеврон в манифесте, а количество их слотов нельзя изменять в игре.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "Количество доступных мест в этом слоте при старте раунда. Экипаж может изменить его в игре, но не более чем вдвое.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"spawn_time_coeff": {
			"title": "Коэффициент Времени Спавна",
			"type": "number",
			"description": "Множитель, используемый для расчёта минимального времени игры в живом состоянии, необходимого для спавна этого корабля.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Коэффициент Времени Офицера",
			"type": "number",
			"description": "Множитель, определяющий минимальное время игры в живом состоянии, необходимое для спавна в офицерской должности на этом корабле.",
			"minimum": 0,
			"default": 1
		}
	},
		"required": [
		"map_name",
		"map_short_name",
		"map_path",
		"faction",
		"job_slots"
	]
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/pirate_crying_sun.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Crying Sun-class Light Frigate",
	"map_short_name": "Crying-Sun",
	"description": "Легкий фрегат производства Nanotrasen для перевозки массивных линейных боевых орудий при сохранении высокой маневренности. Оружейная установка на этом корабле была выведена из эксплуатации, как и многие другие подобные корабли, отправленные из пространства Каликскии. Класс «Crying Sun» — это судно, предназначенное для военно-морского и морского флота, на борту которого находится шаттл для абордажа, экскурсий и передовой разведки. После вывода из эксплуатации основного орудия двигатели были заменены на меньшую мощность, щедро поставлено инженерное оборудование. Так как этот корабль не заимел популярности, его производство было прекращено, а все оставшиеся корабли списаны. Но всё таки некоторые экземпляры смогли попасть на чёрный рынок, а далее и в руки любителей нелегальной деятельности.",
	"map_path": "_maps/_mod_celadon/shuttles/pirate/pirate_crying_sun.dmm",
	"subshuttle": "Nail",
	"enabled": true,
	"limit": 1,
	"sensor_range": 5,
	"space_spawn": true,
	"prefix": "RSV",
	"faction": "/datum/faction/pirate",
	"tags": [
		"Combat",
		"Subshuttle",
		"RP Focus"
	],
		"namelists": [
		"PIRATES",
		"BRITISH_NAVY"
	],
	"job_slots": {
		"Pirate Captain": {
			"outfit": "/datum/outfit/job/independent/captain/pirate/jupiter",
			"officer": true,
			"slots": 1
		},
		"Marine Sergeant": {
			"outfit": "/datum/outfit/job/independent/security/pirate/jupiter",
			"slots": 1
		},
		"Marine": {
			"outfit": "/datum/outfit/job/independent/security/pirate",
			"slots": 3
		},
		"Pirate Engineer": {
			"outfit": "/datum/outfit/job/independent/engineer/pirate/jupiter",
			"slots": 1
		},
		"Pirate Doctor": {
			"outfit": "/datum/outfit/job/independent/doctor/pirate",
			"slots": 1
		},
		"Pirate Crew": {
			"outfit": "/datum/outfit/job/independent/assistant/pirate/jupiter",
			"slots": 2
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/independent_byo.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "BYO-class Do-It-Yourself Enthusiast Special",
	"map_short_name": "BYO",
	"description": "При первоначальном развертывании BYO едва ли можно считать 'судном'; скорее это строительная платформа, запущенная в опасный космос. Единственное, что отделяет экипаж судна BYO от дышащей безопасности и холодного вакуума космоса, - это, как правило, маленькие герметичные заслонки из пластика. Оснащенные множеством строительных материалов и инструментов, пригодных для строительства, судна BYO имеют самые разные формы и размеры, но почти никогда не отличаются постоянством формы.",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_byo.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 2,
	"prefix": "ЕSV",
	"faction": "/datum/faction/independent",
	"tags": [
		"Инженерный",
		"Творческий"
	],
	"namelists": [
		"ENGINEERING",
		"GENERAL"
	],
	"job_slots": {
		"Architect": {
			"outfit": "/datum/outfit/job/independent/ce",
			"slots": 1
		},
		"Mechanic": {
			"outfit": "/datum/outfit/job/independent/engineer",
			"slots": 3
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/solfed_fist_of_freedom.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Fist of Freedom-class Administrative Battleship",
	"map_short_name": "Fist",
	"description": "Платформа “Длань” - это современная универсальная платформа для создания кораблей широкого спектра задач, от авианесущих крейсеров, до боевых, тяжеловооруженных артиллерийских линкоров. Данный корабль имеет компоновку `Кулак Свободы`. Это линкор, используемый для установления контроля военной администрации флота над малонаселенными системами, для поддержания порядка, борьбы с преступностью, пиратством и терроризмом. Этот корабль оснащён самым современным генератором энергии, имеет на борту хорошо вооруженное отделение морской пехоты, а также оборудованием для автономного существования без регулярных продовольственных и ресурсных поставок. Всё что нужно для наведения порядка в системе Адмиралу флота, который наделён особыми полномочиями командования всеми судами Солнечной Федерации.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_fist_of_freedom.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 5,
	"prefix": "ASFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["Командование", "Бой", "Флагман"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"WEAPONS",
		"NATURAL"
	],
	"job_slots": {
		"Flottenadmiral": {
			"outfit": "/datum/outfit/job/solfed/captain/admiral",
			"officer": true,
			"slots": 1
		},
		"Personalvorgesetzter": {
			"outfit": "/datum/outfit/job/solfed/hop",
			"officer": true,
			"slots": 1
		},
		"Feldwebel": {
			"outfit": "/datum/outfit/job/solfed/sergeant",
			"officer": true,
			"slots": 1
		},
		"Marine": {
			"outfit": "/datum/outfit/job/solfed/marine",
			"slots": 6
		},
		"Meeresarzt": {
			"outfit": "/datum/outfit/job/solfed/doctor",
			"slots": 2
		},
		"Marinemechaniker": {
			"outfit": "/datum/outfit/job/solfed/engineer",
			"slots": 2
		},
		"Gehilfe": {
			"outfit": "/datum/outfit/job/solfed/assistant",
			"slots" : 3
		},
		"Contracted Miner": {
			"outfit": "/datum/outfit/job/solfed/miner",
			"slots": 3
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/syndicate_gorlex_sunset.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Sunset-class Warship",
	"map_short_name": "Sunset",
	"description": " «Sunset» — созданный корабль на основе уроков межкорпоративных войн для замены устаревших типов кораблей класса «Komodo». Он представляет собой новейший средний боевой корабль, сочетающий в себе компактность, надёжность и скорость, идеально подходящий для быстрых и маневренных операций в любой ситуации.  На борту носит группу из 5 элитных бойцов, каждый из которых является мастером в своём деле.",
	"map_path": "_maps/_mod_celadon/shuttles/syndicate/syndicate_gorlex_sunset.dmm",
	"enabled" : true,
	"limit": 1,
	"sensor_range": 4,
	"faction": "/datum/faction/syndicate",
	"prefix": "BSSV",
	"tags": [
		"Боевой"
	],
	"namelists": [
		"GORLEX",
		"NATURAL_AGGRESSIVE"
	],
	"job_slots": {
		"Squad Leader": {
			"outfit": "/datum/outfit/job/syndicate/captain/gorlex",
			"officer": true,
			"slots": 1
		},
		"Combat Medic": {
			"outfit": "/datum/outfit/job/syndicate/doctor/gorlex",
			"slots": 1
		},
		"Combat Engineer": {
			"outfit": "/datum/outfit/job/syndicate/engineer/gorlex",
			"slots": 1
		},
		"Commando": {
			"outfit": "/datum/outfit/job/syndicate/security/gorlex",
			"slots": 2
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/independent_bulk_track.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Bulk track ship",
	"map_short_name": "Bulk",
	"description": "Судно типа Bulk, предназначено для перевозки жидкостей, газов, на дальние растояния. По сути, это космический дальнобойщик. На данном судне также есть небольшой грузовой отсек для иных грузоперевозок. Компания делающая данные судна, вскоре после продажи пары суден Bulk, обанкротилась и закрылась, после нескольких судов о несоблюдении технологии постройки суден и нарушения электробезопасности. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Экспериментальный шип!",
	"map_path": "_maps/_mod_celadon/shuttles/misc/independent_bulk.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": [
		"Инженерный"
		],
	"namelists": [
		"GENERAL",
		"SPACE",
		"MYTHOLOGICAL"
		],
	"job_slots": {
			"Driver": {
				"outfit": "/datum/outfit/job/independent/captain/masinyane",
				"slots": 1
			},
			"Pilot": {
				"outfit": "/datum/outfit/job/independent/cargo_tech",
				"slots": 1
			}
		}
	}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/independent_halftrack.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Halftrack-class Merchant Vessel",
	"map_short_name": "Halftrack",
	"description": "Редкое явление в Приграничье (но желанное), судно класса Halftrack - это сильно модернизированный вариант спасательного судна класса Li Tieguai, используемое в качестве передвижного магазина огнестрельного оружия предприимчивыми торговцами оружием повсюду. Если первоначальные варианты судна были скорее просто 'Li Tieguai', а медицинские приспособления были удалены и заменены оружейными стойками и шкафами для боеприпасов, то современная версия 'Halftrack' оснащена стрельбищем, сертифицированной службой безопасности InteQ и централизованным торговым залом, идеальным для демонстрации товаров и одновременного обеспечения их безопасности. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: ШИП НАХОДИТЬСЯ НА ДОРАБОТКЕ БАЛАНСА!",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_halftrack.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": [
	"Торговый",
	"РП Фокус"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/independent/captain",
			"slots": 1
		},
		"IRMG Vanguard": {
			"outfit": "/datum/outfit/job/inteq/captain",
			"officer": true,
			"slots": 1
		},
		"IRMG Enforcer": {
			"outfit": "/datum/outfit/job/inteq/security",
			"slots": 2
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/independent_skipjack.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Skipjack ship",
	"map_short_name": "Skipjack",
	"description": "Новая и секретная разработка воксов! Все совершенные технологии воксов собраны на этом корабле. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Не доработан!",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_skipjack.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": [
		"Survival"
	],
	"namelists": [
		"SPACE",
		"WEAPONS"
	],
	"job_slots": {
		"Loner": {
			"outfit": "/datum/outfit/job/independent/assistant",
			"officer": true,
			"slots": 1
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/independent_alone.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Alone ship",
	"map_short_name": "Alone",
	"description": "Бюджетный корабль, предназначенный для опытных исследователей космоса.",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_alone.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 3,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": [
	"Выживание"
	],
	"namelists": [
		"SPACE",
		"MYTHOLOGICAL"
	],
	"job_slots": {
		"Loner": {
			"outfit": "/datum/outfit/job/independent/assistant",
			"officer": true,
			"slots": 1
		}
	}
}
