=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Схема Конфигурации Корабля",
	"description": "Конфигурация корабля, используемая для определения новых классов кораблей.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Название Класса",
			"type": "string",
			"description": "Название класса корабля, отображаемое в игре. Суффикс «-class» должен быть в нижнем регистре."
		},
		"map_short_name": {
			"title": "Сокращённое Название Класса",
			"type": "string",
			"description": "Сокращённая версия названия класса корабля, используется, например, в манифесте, а также используется для просмотр карт при покупке корабля, ссылаясь на сайт https://map.celadon.pro. Пробелы и символы запрещены. Исключения:'-' и '_'",
			"maxLength": 20
		},
		"description": {
			"title": "Описание Класса",
			"type": "string",
			"description": "Описание класса корабля. В настоящее время отображается показывается для игроков перед покупкой корабля, а также для администраторов в инструментах управления шаттлом.",
			"minLength": 250
		},
		"map_path": {
			"title": "Путь к Файлу Карты",
			"type": "string",
			"description": "Путь к файлу карты данного класса корабля. Используйте прямые слэши (/) для директорий и включайте расширение .dmm. Файлы карт должны находиться в папке '_maps/_mod_celadon'.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"subshuttle": {
			"title": "Название Субшаттла",
			"type": "string",
			"description": "Название Субшаттла, что добавлен на карту материнского корабля. Используется для дополнительного вывода информации при покупке корабля, а также для ссылки на карту субшаттла на сайте корабля."
		},
		"enabled": {
			"title": "Доступность",
			"type": "boolean",
			"description": "Можно ли выбрать этот корабль игрокам. Админы всё равно смогут его заспавнить.",
			"default": false
		},
		"roundstart": {
			"title": "Случайный Выбор на Старте Раунда",
			"type": "boolean",
			"description": "Определяет, может ли этот корабль быть случайно выбран в качестве бесплатного стартового корабля.",
			"default": false
		},
		"limit": {
			"title": "Ограничение на Спавн Кораблей",
			"type": "integer",
			"description": "Максимальное количество кораблей этого класса, которое может быть заспавнено игроками за раунд.",
			"minimum": 0,
			"maximum": 100,
			"default": 1
		},
		"sensor_range": {
			"title": "Дальность Сенсоров",
			"type": "number",
			"description": "Определяет максимальную дальность сенсоров корабля."
		},
		"starting_funds": {
			"title": "Стартовые Средства Корабля",
			"type": "integer",
			"description": "Количество денег на банковском счёте корабля при старте.",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"space_spawn": {
			"title": "Спавн в Космосе",
			"type": "boolean",
			"description": "Определяет, появится ли корабль в космосе или на аванпосте.",
			"default": false
		},
		"prefix": {
			"title": "Префикс Корабля",
			"type": ["null", "string"],
			"description": "Префикс класса корабля, который добавляется к случайно сгенерированным именам при покупке.",
			"maxLength": 6
		},
		"faction": {
			"title": "Фракция Корабля",
			"type": "string",
			"pattern": "^/datum/faction/(.*)$",
			"description": "Фракция по умолчанию."
		},
		"manufacturer": {
			"title": "Производитель Корабля",
			"type": ["null", "string"],
			"description": "Производитель класса корабля, в данный момент не используется, но будет использоваться в автоматических вики-шаблонах."
		},
		"tags": {
			"title": "Теги Корабля",
			"type": "array",
			"description": "Список тегов, описывающих особенности корабля, которые можно использовать для поиска."
		},
		"namelists": {
			"title": "Списки Имен",
			"type": "array",
			"description": "Список имен, из которого этот класс корабля будет выбирать случайное имя при покупке. Все варианты можно найти в файле ship_names.json.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"NANOTRASEN",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLFED",
					"CMM-GOLD",
					"CMM-BARD",
					"PGF"
				]
			}
		},
		"job_slots": {
			"title": "Рабочие Места",
			"description": "Список рабочих мест, доступных на этом корабле. Первый слот всегда отводится под 'капитана', которым становится покупатель.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "Предустановленная должность, должна совпадать с названием работы в коде (названия работ можно найти в соответствующих файлах)."
					},
					{
						"type": "object",
						"description": "Пользовательская должность, может быть любым названием, но требует указания униформы и количества слотов.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "Название униформы (outfit), которая будет использоваться в этом слоте. Должно быть точным, иначе вызовет ошибку.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Определяет, является ли должность офицерской. Офицерские должности получают шеврон в манифесте, а количество их слотов нельзя изменять в игре.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "Количество доступных мест в этом слоте при старте раунда. Экипаж может изменить его в игре, но не более чем вдвое.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"spawn_time_coeff": {
			"title": "Коэффициент Времени Спавна",
			"type": "number",
			"description": "Множитель, используемый для расчёта минимального времени игры в живом состоянии, необходимого для спавна этого корабля.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Коэффициент Времени Офицера",
			"type": "number",
			"description": "Множитель, определяющий минимальное время игры в живом состоянии, необходимое для спавна в офицерской должности на этом корабле.",
			"minimum": 0,
			"default": 1
		}
	},
		"required": [
		"map_name",
		"map_short_name",
		"map_path",
		"faction",
		"job_slots"
	]
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/pirate_ramzi_rondo.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Rondo-class Assault Vessel",
	"map_short_name": "Rondo",
	"description": "'Rondo' - судно ранее используемое синдикатом как разведывательно, изначально снабжалось системой оптического камуфляжа. Однако из-за несовершенства технологии, любое повреждение экранирования приводило к полному отключению систем, в связи с чем судну требовался длительный ремонт. Ко всему прочему, использование технологии оптического камуфляжа, а тем более его ремонт требовали высокую степень квалификации экипажа, в результате чего система камуфляжа была снята, а сами суда из-за своей малой эффективности отправлены на утилизацию в верфи конструкторского бюро. От полного уничтожения данные суда были спасены во время рейда группировкой Рамзи верфей, благодаря чему некоторые экземпляры попали на черный рынок, а оставшиеся до сих пор находятся во владении некоторых боевых формирований.",
	"map_path": "_maps/_mod_celadon/shuttles/pirate/ramzi_rondo.dmm",
	"enabled" : true,
	"limit": 1,
	"sensor_range": 6,
	"space_spawn": true,
	"prefix": "RSV",
	"faction": "/datum/faction/pirate",
	"tags": [
		"Combat",
		"Riot",
		"RP Focus"
	],
	"namelists": [
		"PIRATES",
		"NATURAL_AGGRESSIVE"
	],
	"job_slots": {
		"Battle Master": {
			"outfit": "/datum/outfit/job/ramzi_clique/captain",
			"officer": true,
			"slots": 1
		},
		"Commando": {
			"outfit": "/datum/outfit/job/ramzi_clique/trooper",
			"slots": 5
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/solfed_tomahawk.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Tomahawk-class Scout Vessel",
	"map_short_name": "Tomahawk",
	"description": "Корабль Солнечной Федерации класса Томагавк служит для фронтовой разведки с боем, cо временем начала космических экспансий 23 века о чем может подсказывать его обшивка. Данный корабль обладает хорошей скоростью, не смотря на свои габариты. На судне предусмотрены рабочие места для двух медиков, трёх полевых инженеров и одного корабельного.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_tomahawk.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"starting_funds": 2000,
	"prefix": "BSFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["Разведка", "Бой", "Шахтёрство"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"BRITISH_NAVY",
		"NATURAL"
	],
	"job_slots": {
		"Kommandant": {
			"outfit": "/datum/outfit/job/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Feldwebel": {
			"outfit": "/datum/outfit/job/solfed/sergeant",
			"officer": true,
			"slots": 1
		},
		"Marine": {
			"outfit": "/datum/outfit/job/solfed/marine",
			"slots": 3
		},
		"Meeresarzt": {
			"outfit": "/datum/outfit/job/solfed/doctor",
			"slots": 2
		},
		"Marinemechaniker": {
			"outfit": "/datum/outfit/job/solfed/engineer",
			"slots": 1
		},
		"Contracted Miner": {
			"outfit": "/datum/outfit/job/solfed/miner",
			"slots": 3
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/nanotrasen_daggerfall.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Daggerfall-class Assault Vessel",
	"map_short_name": "Daggerfall",
	"description": "NTSPSV 'Daggerfall'- Судно Нанотрейзен специального назначения которое был разработано Nakamura Engineering по запросу Vigilitas Interstellar для устранения враждебных криминальных формирований и контроля безопасности активов Nanotrasen. Был введен в эксплутацию как аналог малоэффективного судна 'Bolide', основные функции его предшественника были унаследованы и усовершенствованы. При разработке этого судна Nakamura Engineering за прототип был взят 'Tomahawk' регулярных сил Солнечной Федерации. ",
	"map_path": "_maps/_mod_celadon/shuttles/nanotrasen/nanotrasen_daggerfall.dmm",
	"subshuttle": "Rider",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"starting_funds": 1000,
	"prefix": "NTSPSV",
	"faction": "/datum/faction/nt",
	"tags": [
		"Combat",
		"Riot",
		"Subshuttle"
	],
	"namelists": [
		"NANOTRASEN",
		"WEAPONS"
	],
	"job_slots": {
		"LP Lieutenant": {
			"outfit": "/datum/outfit/job/nanotrasen/captain/lp",
			"officer": true,
			"slots": 1
		},
		"LP Engineering Specialist": {
			"outfit": "/datum/outfit/job/nanotrasen/engineer/lp",
			"officer": true,
			"slots": 1
		},
		"LP Security Operative": {
			"outfit": "/datum/outfit/job/nanotrasen/security/lp",
			"slots": 3
		},
		"LP Medical Specialist": {
			"outfit": "/datum/outfit/job/nanotrasen/doctor/lp",
			"slots": 1
		},
		"LP Survival Specialist": {
			"outfit": "/datum/outfit/job/nanotrasen/miner",
			"slots":1
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/elysium_aldaama.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Aldaama-class Experimental Project",
	"map_short_name": "Aldaama",
	"description": "Изначально 'Алдаама' работал на двигателе Сингулярности, но после ее побега, никто даже не заикался снова ввести ее в эксплуатацию. Вместо этого сделали более безопасный двигатель Тесла. На данный момент у Республики Элизиума всего два таких корабля. Один стоит в музее 'Алехар'(каменистая планета 'Лер'), а второй активно используется сепаратистами Элизиума как корабль снабжения и оперативной телекоммуникационной базой.",
	"map_path": "_maps/_mod_celadon/shuttles/elysium/elysium_aldaama.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "ESV",
	"faction": "/datum/faction/elysium",
	"tags": [
		"Специализированный",
		"Боевой",
		"РП Фокус"
	],
	"namelists": [
		"SPACE",
		"WEAPONS",
		"ENGINEERING"
	],
	"job_slots": {
		"Caid": {
			"outfit": "/datum/outfit/job/elysium/captain",
			"officer": true,
			"slots": 1
		},
		"Ahisa`i": {
			"outfit": "/datum/outfit/job/elysium/assistant",
			"slots": 3
		},
		"Mukatell": {
			"outfit": "/datum/outfit/job/elysium/security",
			"slots" : 2
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/independent_sunskipper.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Sunskipper-class Culinary Vessel",
	"map_short_name": "Sunskipper",
	"description": "Sunskipper-class — это современное кулинарное судно, найденное на границе. Sunskipper с распростертыми объятиями встречают усталые космонавты с более высокими зарплатами, которые утомлены однообразием своих повседневных приемов пищи. На судне есть самоподдерживающаяся кухня с гидропоникой и большой, роскошный обеденный зал, предназначенный для обслуживания голодных путешественников. Он также оснащен полностью укомплектованной баром, который позволяет им выпить свои проблемы, хотя бы на короткое время.",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_sunskipper.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"starting_funds": 3000,
	"prefix": "SV",
	"faction": "/datum/faction/independent",
	"tags": [
		"РП Фокус",
		"Сервисный"
	],
	"namelists": ["CRUISE", "NATURAL"],
	"job_slots": {
		"Manager": {
			"outfit": "/datum/outfit/job/independent/captain/manager",
			"slots": 1,
			"officer": true
		},
		"Bartender": {
			"outfit": "/datum/outfit/job/independent/bartender/disarmed",
			"slots": 1
		},
		"Cook": {
			"outfit": "/datum/outfit/job/independent/cook",
			"slots": 2
		},
		"Waiter": {
			"outfit": "/datum/outfit/job/independent/assistant/waiter",
			"slots": 2
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/syndicate_krait.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Krait-class",
	"map_short_name": "Krait",
	"description": "Универсальный корабль класса 'Крайт', совмещает в себе две команды SnD и RnD. Команда SnD занимается поиском, захватом и уничтожением для второй команды занимающейся исследованиями. Корабль оснащен передовыми нанотехнологиями для более эффективной работы, обладает суб шаттлом для быстрого захвата и уничтожения объектов.",
	"map_path": "_maps/_mod_celadon/shuttles/syndicate/syndicate_krait.dmm",
	"subshuttle": "Jet_lancer",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "RSSV",
	"faction": "/datum/faction/syndicate",
	"tags": ["Combat", "Riot", "Medical", "Genetics", "Subshuttle" ],
	"namelists": ["CYBERSUN", "GORLEX"],
	"job_slots": {
		"Search and Destroy Team Leader": {
			"outfit": "/datum/outfit/job/syndicate/captain/gorlex",
			"officer": true,
			"slots": 1
		},
		"Search and Destroy team member": {
			"outfit": "/datum/outfit/job/syndicate/security/gorlex",
			"slots": 3
		},
		"Research and Development Team Leader": {
			"outfit": "/datum/outfit/job/syndicate/science/Director",
			"officer": true,
			"slots": 1
		},
		"Research and Development team member": {
			"outfit": "/datum/outfit/job/roboticist",
			"slots": 3
		},
		"GEC Engineering": {
			"outfit": "/datum/outfit/job/syndicate/engineer/gec",
			"slots": 2
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/independent_sfwb.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Sfwb-class Space Fleetwood Bounder",
	"map_short_name": "Sfwb",
	"description": "Адаптация автодома Fleetwood Bounder под космос. На этом установлено хим. оборудование. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Ивентовый.",
	"map_path": "_maps/_mod_celadon/shuttles/misc/independent_sfwb.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": [
		"Chemist"
	],
	"namelists": [
		"GENERAL",
		"SPACE",
		"NATURAL"
	],
	"job_slots": {
		"Chem-chef": {
			"outfit": "/datum/outfit/job/chemist",
			"slots": 2
		}
	}
}

=== Mirag1993/Shiptest-voyko/_maps/_mod_celadon/configs/solfed_paracelsus.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Paracelsus-class Medical Corvette",
	"map_short_name": "Paracelsus",
	"description": "Выполняя свою роль медицинского центра соларианского флота, корвет класса 'Paracelsus' специально спроектирован для помощи соларианским флотам в медицинских проблемах, а также для снабжения таких судов медикаментами. Писари, получающие медицинское образование, часто работают на этих суднах, чтобы стать тенью опытных медиков и пройти ординатуру. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Неизвестный и непонятный шип!",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_paracelsus.dmm",
	"enabled": false,
	"sensor_range": 4,
	"limit": 1,
	"prefix": "SFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["RP Focus", "Medical", "Chemistry"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"BRITISH_NAVY",
		"NATURAL"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Overseer": {
			"outfit": "/datum/outfit/job/solfed/overseer",
			"officer": true,
			"slots": 1
		},
		"Medical Doctor": {
			"outfit": "/datum/outfit/job/solfed/doctor",
			"slots": 3
		},
		"Ship Engineer": {
			"outfit": "/datum/outfit/job/solfed/engineer",
			"slots": 1
		},
		"Psychologist": {
			"outfit": "/datum/outfit/job/solfed/psychologist",
			"slots": 1
		},
		"Field Engineer": {
			"outfit": "/datum/outfit/job/solfed/miner",
			"slots": 2
		},
		"Scribe": {
			"outfit": "/datum/outfit/job/solfed/assistant",
			"slots" : 3
		},
		"Attentive Care Patient": {
			"outfit": "/datum/outfit/job/solfed/patient",
			"slots" : 3
		}
	}
}
